# section 16 lecture 233 234
sudo: required
services:
  - docker
# set up google cloud on local machine
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.
  # update and install kubectl inside of our travis environment
  - glcoud components update kubectl
  # tell google cloud who we are and give access to our account
  # credentials are inside file `service-account.json` -> created through google clound (create a service account)
  # down load file as json and upload to travis
  - gcloud auth activate-service-account --key-file service-account.json
